// agents/selfCriticAgent.js

/**
 * Reviews a generated command and fixes it if necessary.
 * The model acts as a second-pass validator.
 */
async function reviewCommand({ client, command, query, platform, shell }) {
  if (!command || typeof command !== 'string') {
    return { command };
  }

  const prompt = `You are reviewing a shell command generated by another AI.

User request:
"${query}"

Operating System: ${platform}
Shell: ${shell || 'unknown'}

Generated command:
${command}

Your task:
1. Verify the command correctly fulfills the user request.
2. Fix mistakes if necessary.
3. Ensure it works for the specified OS and shell.

Output ONLY the corrected command.
Do not include explanation or prose.
If the command is already correct, return it unchanged.
`;

  try {
    const raw = await client.generate({ prompt, maxTokens: 120 });

    if (!raw) {
      return { command };
    }

    const cleaned = raw
      .replace(/```[a-z]*\n?/gi, '')
      .replace(/```/g, '')
      .trim();

    const normalized = cleaned.replace(/\r?\n+/g, ' ').trim();

    if (!normalized || normalized.length > 200) {
      return { command };
    }

    return { command: normalized };
  } catch (err) {
    return { command };
  }
}

module.exports = {
  reviewCommand,
};