const { LangGraph } = require('./langgraph');
const { analyzeIntent } = require('./agents/intentAgent');
const { generateCommand } = require('./agents/commandAgent');
const { validateSafety } = require('./agents/safetyAgent');
const { generateExplanation } = require('./agents/explainAgent');
const { runAgent } = require('./agents/runAgent');

const pipeline = new LangGraph();
const debug = !!process.env.AI_CMD_DEBUG;

pipeline.use(async (state) => {
  if (debug) {
    // eslint-disable-next-line no-console
    console.log('[ai-cmd] pipeline: running intent analysis');
  }
  const intentResult = await analyzeIntent({ query: state.query });
  return { ...state, ...intentResult };
});

pipeline.use(async (state) => {
  if (state.command) {
    // Command already generated by a previous run (e.g. before prompting).
    return state;
  }

  if (debug) {
    // eslint-disable-next-line no-console
    console.log('[ai-cmd] pipeline: generating command');
  }
  const commandResult = await generateCommand({
    intent: state.intent,
    query: state.query,
    context: state.context,
    platform: state.platform,
    shell: state.shell,
  });
  return { ...state, ...commandResult };
});

pipeline.use(async (state) => {
  if (debug) {
    // eslint-disable-next-line no-console
    console.log('[ai-cmd] pipeline: validating safety');
  }
  const safetyResult = await validateSafety({ command: state.command });
  return { ...state, ...safetyResult };
});

pipeline.use(async (state) => {
  if (debug) {
    // eslint-disable-next-line no-console
    console.log('[ai-cmd] pipeline: generating explanation');
  }
  const explanationResult = await generateExplanation({ command: state.command });
  return { ...state, ...explanationResult };
});

pipeline.use(async (state) => {
  if (debug) {
    // eslint-disable-next-line no-console
    console.log('[ai-cmd] pipeline: running command');
  }
  return runAgent(state);
});

async function runPipeline({ query, platform = process.platform, shell, runCommand = false }) {
  return pipeline.run({ query, platform, shell, runCommand });
}

module.exports = {
  runPipeline,
};
